#include "plottypes.h"
#include <cstring>
#include <cassert>

namespace plot {

	FACT_DEFINE_ENUM_STR(E_PlotSymbol,PLOTSYMBOL_ENUM);
	FACT_DEFINE_ENUM_TO_STRING(E_PlotSymbol,PLOTSYMBOL_ENUM);
	FACT_DEFINE_ENUM_FROM_STR(E_PlotSymbol,PLOTSYMBOL_ENUM);
	FACT_DEFINE_ENUM_STR_LN(E_PlotSymbol,PLOTSYMBOL_ENUM);


	FACT_DEFINE_ENUM_STR(E_CurveStyle,CURVESTYLE_ENUM);
	FACT_DEFINE_ENUM_FROM_STR(E_CurveStyle,CURVESTYLE_ENUM);
	FACT_DEFINE_ENUM_STR_LN(E_CurveStyle,CURVESTYLE_ENUM);
}
